{
 "title": "33 - Dashboard monitoramento active directory desktop resumo.(Módulo-18)",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": {}
   },
   {
    "name": "Hosts",
    "label": "Controlador de Dominio",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Informações dos ativos do active directory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Quantidade por sistema operacional windows server",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de computadores/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Server/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade por sistema operacional windows desktop.",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de computadores/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Windows/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de usuarios logados nos servidores.",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "application": { "filter": "/Windows Server/" },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de usuarios logados no desktops.",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "application": {
      "filter": "/Windows 10|Windows 7| Windows 8| Windows XP/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de desktops sem logar + 30 dias.",
   "type": "table",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "application": {
      "filter": "/Relacao de desktops e servidores/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/.*/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}