{
 "title": "11 - Dashboard Fortigate basico",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Informacoes de disponibilidade", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidade",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": { "filter": "Disponibilidade" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latencia",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": { "filter": "Latencia" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Perda de pacote",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "pps",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": { "filter": "Perda de Pacote ( porcentagem)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Informacoes de Disponibilidade" },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": { "filter": "Tempo Ligado" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informacoes de recursos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Uso de CPU %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de uso do processador FortiGate-VM64-CURSO"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Informacoes de uso do processador do Firewall FortiGate-VM64-CURSO"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uso de Memoria %",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de uso de memoria do Firewall 1"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Informacoes de uso de memoria do Firewall FortiGate-VM64-CURSO"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de servicos em execução!",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de inventario de hardware Curso"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Quantidade de servicos em execucao no Firewall Curso"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de placas de rede",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de inventario de hardware Curso"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Quantidade de Interface de rede no Firewall Curso"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informacoes de inventario", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Numero de serie",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de inventario do Firewall 1"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Numero de Serie do Firewall FortiGate-VM64-CURSO"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de H.A do Firewall 0"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Hostname do Firewall Master FortiGate-VM64-CURSO"
     },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status de checagem de link",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de checagem do link de internet do Firewall 1"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Status de checagem de link de internet 1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informacoes de trafego de rede", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Download Port1 (LAN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Informacoes de interface de rede 1"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Trafego de Entrada na interface port1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload Port1 (LAN)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": {
      "filter": "Informacoes de interface de rede 1"
     },
     "group": { "filter": "Hosts/Fortinet" },
     "host": { "filter": "FIREWALL-FORTIGATE" },
     "item": {
      "filter": "Trafego de Saida na interface port1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}