{
 "title": "17 - Dashboard Servidor de arquivos",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Group", "label": "Group", "query": "*" },
   { "name": "Hosts", "query": "$Group.*" },
   { "name": "Pasta", "label": "Pasta", "query": "$Group.$Hosts.*" }
  ]
 },
 "panels": [
  {
   "title": "Local de hospedagem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Cota aplicada a pasta/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Quantidade de arquivos",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Quantidade de arquivos/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaco usado em %",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Uso da pasta em porcentagem/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local de hospedagem",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 13, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Local de hospedagem da pasta/" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cota aplicada",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 4 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Tamanho da pasta/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Espaco usado",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 4 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Espaco usado da pasta/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Evolução da pasta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Espaco usado da pasta/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Evolução Quantidade de arquivos",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "$Pasta" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Quantidade de arquivos" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}