{
 "title": "2 - Dashboard  Servicos do office 365 básico.(Módulo-12)",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Informacoes dos servicos do office 365",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Normal service.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de servicos/"
     },
     "group": { "filter": "OFFICE 365" },
     "host": { "filter": "LLK85N119D9D" },
     "item": { "filter": "/Normal service/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Restoring service.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de servicos/"
     },
     "group": { "filter": "OFFICE 365" },
     "host": { "filter": "LLK85N119D9D" },
     "item": { "filter": "/Restoring service/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Service degradation.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de servicos/"
     },
     "group": { "filter": "OFFICE 365" },
     "host": { "filter": "LLK85N119D9D" },
     "item": { "filter": "/Service degradation/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Service restored.",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de quantidade de servicos/"
     },
     "group": { "filter": "OFFICE 365" },
     "host": { "filter": "LLK85N119D9D" },
     "item": { "filter": "/Service restored/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "application": { "filter": "/Informacoes do servico/" },
     "group": { "filter": "OFFICE 365" },
     "host": { "filter": "LLK85N119D9D" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}