{
 "title": "41 - Dashboard monitoramento firewall fortigate (Módulo-07) 3 Treinamento",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Grupo",
    "label": "Grupo",
    "query": {}
   },
   {
    "name": "Firewall",
    "label": "Firewall",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Informações do firewall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Versao do sistema",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Versao do sistema/" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Quantidade de processadores logicos",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 8, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": {
        "filter": "/Quantidade de processadores logicos/"
       },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacidade da memoria",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Capacidade da memoria/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Capacidade do disco",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Capacidade do disco/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Localizacao",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Localizacao/" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Uso da cpu em %",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 6, "x": 8, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Uso da cpu em %/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Uso da memoria em %",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 14, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Uso da memoria em %/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Disco usado",
     "type": "bargauge",
     "gridPos": { "h": 3, "w": 5, "x": 19, "y": 4 },
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Disco usado/" },
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Contato",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "application": { "filter": "/Informacoes do firewall/" },
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Firewall" },
       "item": { "filter": "/Contato/" },
       "mode": 2,
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    }
   ]
  },
  { "title": "Informacoes de trafego de rede", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total de trafego do firewall",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/Total de trafego da/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego de entrada do firewall",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/Trafego de entrada da/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Trafego de saida do firewall",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de trafego de rede da/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/Trafego de saida da/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informações de status dos links de internet!",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de monitoramento do link de internet/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/Status do/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  { "title": "Informações de proteção", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Informacoes de Antivirus do firewall.",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de Antivirus do firewall/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informacoes de IPS do firewall",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "application": {
      "filter": "/Informacoes de IPS do firewall/"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Firewall" },
     "item": { "filter": "/.*/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}