{
 "title": "18 - Dashboard Switch",
 "description": "Material do Treinamento da 2MTI Treinamentos & Serviços.\n\nSite:\n\nhttps://maratonadainfra.kpages.online/",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Grupo", "query": "*" },
   { "name": "Host", "query": "$Grupo.*" }
  ]
 },
 "panels": [
  {
   "title": "Status administrativo das interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Gi0/1",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/2",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/3",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/4",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/5",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/6",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/7",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/7"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/8",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/8"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/9",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/9"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/10",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/10"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/11",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/11"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/12",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/12"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/13",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/13"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/14",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/14"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/15",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/15"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/16",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/6"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/17",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/17"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/18",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/18"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/19",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/19"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/20",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/20"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/21",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/21"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/22",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/22"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/23",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/23"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Gi0/24",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Status Administrativo das Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Status administrativo da interface GigabitEthernet0/24"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Informações de download x upload dos uplinks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "title": "Download Gi1/1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Entrada na Interface de Rede GigabitEthernet1/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download Gi1/2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Entrada na Interface de Rede GigabitEthernet1/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download Gi1/3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Entrada na Interface de Rede GigabitEthernet1/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Download Gi1/4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Entrada na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Entrada na Interface de Rede GigabitEthernet1/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload Gi1/1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Saida na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Saida na Interface de Rede GigabitEthernet1/1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload Gi1/2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Saida na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Saida na Interface de Rede GigabitEthernet1/2"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload Gi1/3",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Saida na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Saida na Interface de Rede GigabitEthernet1/3"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Upload Gi1/4",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "application": {
      "filter": "Informacoes de Trafego de Saida na Interface de Rede"
     },
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": {
      "filter": "Tráfego de Saida na Interface de Rede GigabitEthernet1/4"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}