{
 "title": "Dashboard GLPI based on MySql request",
 "description": "Some MySql request, timeseries working.",
 "tags": [ "GLPI MYSQL" ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_GLPI", "label": "GLPI Datasource", "query": "ddurieux-glpi-datasource" },
   { "name": "URL_GLPI", "query": "${VAR_URL_GLPI}" }
  ]
 },
 "panels": [
  {
   "title": "Top catégorie des tickets",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT glpi_itilcategories.completename as 'Nom catégorie',\ncount(DISTINCT glpi_tickets.name) as 'Nombre tickets' \nFROM glpi_tickets \ninner join glpi_itilcategories on glpi_tickets.itilcategories_id = glpi_itilcategories.id \nWHERE $__timeFilter(date) and glpi_tickets.is_deleted = '0' \nGroup by glpi_itilcategories.name \nORDER BY `Nombre tickets` DESC"
    }
   ]
  },
  {
   "title": "Top catégorie des demandes",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT glpi_itilcategories.completename as 'Nom catégorie',\ncount(DISTINCT glpi_tickets.name) as 'Nombre tickets' \nFROM glpi_tickets\ninner join glpi_itilcategories on glpi_tickets.itilcategories_id = glpi_itilcategories.id \nWHERE $__timeFilter(date) and glpi_tickets.is_deleted = '0'  and glpi_tickets.type = 2\nGroup by glpi_itilcategories.name \nORDER BY `Nombre tickets` DESC"
    }
   ]
  },
  {
   "title": "Top catégorie des incidents",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT glpi_itilcategories.completename as 'Nom catégorie',\ncount(DISTINCT glpi_tickets.name) as 'Nombre tickets' \nFROM glpi_tickets \ninner join glpi_itilcategories on glpi_tickets.itilcategories_id = glpi_itilcategories.id \nWHERE $__timeFilter(date) and glpi_tickets.is_deleted = '0'  and glpi_tickets.type = 1\nGroup by glpi_itilcategories.name \nORDER BY `Nombre tickets` DESC"
    }
   ]
  },
  {
   "title": "Evolutions des tickets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n@rownum := @rownum + 1 as \"Nombre d'incidents\",\r\ndate as time\r\nfrom glpi_tickets \r\ncross join (select @rownum := 0) r \r\nWHERE $__timeFilter(date) and type = 1 and glpi_tickets.is_deleted = '0' \r\norder by date\r\n"
    },
    {
     "rawSql": "select \r\n@rownum := @rownum + 1 as \"Nombre de demandes\",\r\ndate as time\r\nfrom glpi_tickets \r\ncross join (select @rownum := 0) r \r\nWHERE $__timeFilter(date) and type = 2 and glpi_tickets.is_deleted = '0' \r\norder by date\r\n"
    },
    {
     "rawSql": "select \r\n@Total := @Total + 1 as Total,\r\ndate as time\r\nfrom glpi_tickets \r\ncross join (select @Total := 0) r \r\nWHERE $__timeFilter(date) and glpi_tickets.is_deleted = '0' \r\norder by date\r\n"
    }
   ]
  },
  {
   "title": "Evolutions du parc informatique",
   "type": "graph",
   "description": "Nombre de postes gérés",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select \r\n@rownum := @rownum + 1 as \"Nombre de postes\",\r\ndate_creation as time\r\nfrom glpi_computers\r\ncross join (select @rownum := 0) r \r\nWHERE $__timeFilter(date_creation) and is_deleted = 0\r\norder by date_creation\r\n"
    },
    {
     "rawSql": "select \r\n@rownum := @rownum + 1 as \"Nombre d'utilisateurs\",\r\ndate_creation as time\r\nfrom glpi_users\r\ncross join (select @rownum := 0) r \r\nWHERE $__timeFilter(date_creation) and is_deleted = 0\r\norder by date_creation\r\n"
    }
   ]
  },
  {
   "title": "Incidents / Demandes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ncount(distinct id) as \"Nombre d'incidents\"\nFROM glpi_tickets\nWHERE\n  $__timeFilter(date) and type = 1 and is_deleted = 0\nGroup BY type"
    },
    {
     "rawSql": "SELECT\ncount(distinct id) as \"Nombre de demandes\"\nFROM glpi_tickets\nWHERE\n  $__timeFilter(date) and type = 2 and is_deleted = 0\nGroup BY type"
    }
   ]
  },
  {
   "title": "Sources des sollicitations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT glpi_requesttypes.name as 'Sources',\ncount(DISTINCT glpi_tickets.name) as 'Nombre tickets' \nFROM glpi_tickets\ninner join glpi_requesttypes on glpi_tickets.requesttypes_id = glpi_requesttypes.id \nWHERE $__timeFilter(date) and glpi_tickets.is_deleted = '0'\nGroup by glpi_requesttypes.name \nORDER BY `Nombre tickets` DESC"
    }
   ]
  }
 ]
}